name: Atualização Diária dos Dados do IBAMA

on:
  # Permite que você rode este workflow manualmente a partir da aba Actions no GitHub
  workflow_dispatch:

  # Agenda a execução para todos os dias às 13:00 UTC (10:00 no horário de São Paulo, UTC-3)
  schedule:
    - cron: '0 13 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest # Usa a versão mais recente do Ubuntu como ambiente

    steps:
      # Passo 1: Faz o checkout do código do seu repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Python
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Passo 3: Instala todas as dependências do projeto
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Executa o script de upload para o Supabase
      - name: Executar script de upload
        run: python upload_to_supabase.py
        env:
          # Mapeia os segredos do GitHub para variáveis de ambiente que o script usará
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          # A URL do IBAMA pode ser passada como variável de ambiente também, para consistência
          IBAMA_ZIP_URL: 'https://dadosabertos.ibama.gov.br/dados/SIFISC/auto_infracao/auto_infracao/auto_infracao_csv.zip'
