name: Atualização Diária dos Dados do IBAMA

on:
  # Permite que você rode este workflow manualmente a partir da aba Actions no GitHub
  workflow_dispatch:
  # Agenda a execução para todos os dias às 13:00 UTC (10:00 no horário de São Paulo, UTC-3)
  schedule:
    - cron: '0 13 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Timeout de segurança
    
    steps:
      # Passo 1: Faz o checkout do código do seu repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Python
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'  # Cache das dependências para acelerar

      # Passo 3: Instala apenas as dependências necessárias para o upload
      - name: Instalar dependências essenciais
        run: |
          python -m pip install --upgrade pip
          pip install pandas supabase requests urllib3

      # Passo 4: Executa o script de upload standalone
      - name: Executar script de upload
        run: python upload_to_supabase_standalone.py
        env:
          # Mapeia os segredos do GitHub para variáveis de ambiente
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          IBAMA_ZIP_URL: 'https://dadosabertos.ibama.gov.br/dados/SIFISC/auto_infracao/auto_infracao/auto_infracao_csv.zip'

      # Passo 5: Upload de logs em caso de falha (opcional)
      - name: Upload de logs em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            *.log
            **/*.log
          retention-days: 7
