name: 🌳 Atualização IBAMA - Schema Corrigido
on:
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Forçar atualização mesmo com erros menores'
        required: false
        default: 'false'
        type: boolean
      debug_mode:
        description: 'Ativar modo debug detalhado'
        required: false
        default: 'false'
        type: boolean
  
  schedule:
    - cron: '0 13 * * *'  # 13:00 UTC = 10:00 BRT

jobs:
  update-data-corrected:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: 📁 Checkout do repositório
        uses: actions/checkout@v4
        
      - name: 🐍 Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: 📦 Instalar dependências otimizadas
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pandas==2.2.3 supabase==2.5.0 requests==2.32.3 urllib3==2.2.2
          
      - name: 🔍 Verificar ferramentas de sistema
        run: |
          echo "🔧 Verificando ferramentas disponíveis:"
          which wget && echo "✅ wget: $(wget --version | head -1)" || echo "❌ wget não disponível"
          which curl && echo "✅ curl: $(curl --version | head -1)" || echo "❌ curl não disponível"
          
          echo "🌐 Testando conectividade:"
          ping -c 3 dadosabertos.ibama.gov.br || echo "⚠️ Ping falhou"
          
      - name: 🔍 Debug - Verificar Supabase Schema
        if: ${{ inputs.debug_mode == 'true' }}
        run: |
          python -c "
          import os
          from supabase import create_client
          
          try:
              supabase = create_client('${{ secrets.SUPABASE_URL }}', '$
